[package]
name = "couch-lang-parser"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
couch-lang-lexer = { version = "0.1.0", path = "../lexer" }

[dev-dependencies]
pretty_assertions = "1.3.0"
